### ISSUE TITLE
libmediainfo.so.0 => not found (on hosting system)

### ISSUE THREAD

**Issue by ashtrakhov** [xbgmsharp/piwigo-videojs#102]
Hi,
I followed your wiki "Using MediaInfo, ffmpeg without installing it inside the hosting system" but I'm getting following dependency errors:

ldd usr/bin/mediainfo
	linux-vdso.so.1 =>  (0x00007ffe79b68000)
	**libmediainfo.so.0 => not found**
	libz.so.1 => /lib64/libz.so.1 (0x0000003fd7800000)
	**libzen.so.0 => not found**

Im on CentOS release 6.8
I downloaded zip provided in the article

**Comment by xbgmsharp** [comment]
I believe you refer to https://github.com/xbgmsharp/piwigo-videojs/wiki/Using-MediaInfo%2C-ffmpeg-without-installing-it-inside-the-hosting-system
Do you have root access? If so you need to install the mediainfo package as well as the library.
If not how did you install mediainfo? From the Zip? did you unzip it inside ``/usr/``?
If not you probably need to add the full path of the unzip library ``$ echo `pwd`/usr/lib64/`` to the ``LD_LIBRARY_PATH=.:/var/www/....``

**Comment by ashtrakhov** [comment]
sorry I'm not a very good at this... i guess I'm doing something completely wrong
im not a root...

I have unzipped provided package in 
/home4/shtrakho/public_html/fotos/usr/

I did add full path to :# echo $LD_LIBRARY_PATH 
:/home4/shtrakho/public_html/fotos/usr/bin/mediainfo

still getting like this:
# ldd usr/bin/mediainfo
	linux-vdso.so.1 =>  (0x00007ffd583b8000)
	libmediainfo.so.0 => not found
	libz.so.1 => /lib64/libz.so.1 (0x0000003fd7800000)
	libzen.so.0 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003fd6c00000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x0000003fdac00000)
	libm.so.6 => /lib64/libm.so.6 (0x0000003fd6800000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003fd8400000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003fd6400000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003fd6000000)

**Comment by darenwelsh** [comment]
I also tried this method of copying and unpacking the zip file with the same results. I also do not have root access nor do I have access to create or modify files in /usr. For FFMPEG, I was able to find a binary that I could just copy into my /home/<username> directory. Is there a way to do that with mediainfo?

**Comment by xbgmsharp** [comment]
You will need to add an env variable LD_LIBRARY_PATH.
```
echo $LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/
echo $LD_LIBRARY_PATH
```

https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux#13428971

**Comment by xbgmsharp** [comment]
no reply closing.

**Comment by rajdude** [comment]
Whooo hooo! THANK YOU :-) 
At least I got rid of the not found errors. I used  your suggestion to set path.

echo $LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/raj/mediainfo/usr/lib64
echo $LD_LIBRARY_PATH

But I guess this path will be only for this terminal session. I mean it will not survive after I log off.
