### ISSUE TITLE
Debian 8, ffmpeg/avconv unable to find a suitable output format

### ISSUE THREAD

**Issue by EddyLB** [xbgmsharp/piwigo-videojs#108]
For some videos, posters are not produced and I get the following log:
```
avconv version 11.9-6:11.9-1~deb8u1, Copyright (c) 2000-2017 the Libav developers
  built on Apr 23 2017 21:47:31 with gcc 4.9.2 (Debian 4.9.2-10)
Unable to find a suitable output format for '/dev/null'
```
However, sending this command manually works fine:
`avconv -itsoffset -0 -i 20170618132520-c78f7510.m4v  -vcodec png -vframes 1 -an -f rawvideo -y test.png`

Any idea how to fix this ?

**Comment by achanler** [comment]
I am getting the same issue.  I just posted my error log to issue #103 which is also for 'unable to find a suitable output format'.

**Comment by EddyLB** [comment]
I solved this issue by installing a fresh version of the 'true' [FFmpeg](http://www.ffmpeg.org) and updating Piwigo with this [fix](https://github.com/Piwigo/Piwigo/pull/756).
