### ISSUE TITLE
Problem with mediainfo17.**

### ISSUE THREAD

**Issue by beuldi** [xbgmsharp/piwigo-videojs#113]
hi everyone
i have a problem with the plugin after updating mediainfo to 17.10 or 17.12.

> Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 127
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 128
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 129
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 137
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 139
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 156
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 156
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line 156
Trying to get property of non-object in /var/www/piwigo/plugins/piwigo-videojs/admin/admin_photo.php on line <

downgarding to version 0.7.99 solve the problem. but is this the only way to fix it?

Regards

beuldi

**Comment by tsmig** [comment]
Hi, I have similar issue.
I think that error appears because of mediainfo version that is supported by plugin.
On CentOS (and other recent distributions) mediainfo (v17.12)  has XML output format, that is not covered by this plugin.

**Comment by jradwan** [comment]
I had a similar issue (after a Ubuntu upgrade which included mediainfo 17.12). Downgrading to 0.7.87 resolved the problem for me.

**Comment by xbgmsharp** [comment]
mediainfo 17.x and mediainfo 18.x are now supported.

**Comment by xbgmsharp** [comment]
admin_photo.tpl does not rely on MediaInfo anymore.
Solved with v2.9.a
