### ISSUE TITLE
Support of .3gp and .3g2 extensions

### ISSUE THREAD

**Issue by Tontonitch** [xbgmsharp/piwigo-videojs#117]
Hello,
I have some users that take videos using their smartphones in the 3GP format.
Unfortunately, it is currently not supported by your extension.
Are there any chance to see these formats (3GP, 3G2) supported by your extension? That would be great, as the users that I'm talking about won't know / understand how to convert 3GP files to MP4 for example, so having the possibility to directly upload and play 3GP files in piwigo would be great!
BR,
Yannick

**Comment by xbgmsharp** [comment]
Hello,
It used be the case,  but unfortunately, it is not supported anymore as it require the flash player. Those formats (3GP, 3G2) should be converted to MP4 (H264/AAC) as there are derivate anyway.
I would suggest to convert using FFMPEG or HandBrakeCLI, see wiki, https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#issue-content-you-know

We could convert on upload.

**Comment by xbgmsharp** [comment]
An alternative, to convert but not idela would be add the flash player fallback.
https://www.npmjs.com/package/videojs-flash

**Comment by xbgmsharp** [comment]
The problem is not to sync .3gp and .3g2 files. VideoJs does not play 3gp and .3g2 as it is not a web standard HTML5 video format. You will need to transcode your video into MP4 H264 or others HTML5 video format using HandBrake https://github.com/HandBrake/HandBrake
https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#issue-content-you-know

**Comment by anjaneyulugulla** [comment]
i have issue for web in vedos in .3gp formats.
so any solution this format in plugins

**Comment by miklosbagi** [comment]
For all still looking to add .3gp/.3g2, example one-liner to convert all recursively with ffmpeg.

Prerequisites:
- use linux (even in vm, or raspberry pi)
- have ffmpeg installed
- navigate to the directory where your 3gp files are
 
```
OLDIFS="$IFS"; IFS=$'\n'; for f in `find . -type f -name *.3[gG][pP2]`; do nf=`echo "$f" |sed 's#\.3[gG][pP2]$#\.mp4#'`; ffmpeg -i "$f" -vcodec h264 -acodec aac "$nf" && rm "$f"; done; IFS="$OLDIFS"
```

Hope that helps
