### ISSUE TITLE
Issues with FFMPEG and mediainfo

### ISSUE THREAD

**Issue by nigel-aves** [xbgmsharp/piwigo-videojs#119]
**ffmpeg - 2.6.8-3.el7.nux**

I am able to create a poster at the number of seconds specified, so it looks like ffmpeg is reading the .MP4 correctly.

But I am unable to create any  thumbnails. No message or anything like that. (I have checked and no files generated).

mediainfo - 18.03-1.el7
   	libmediainfo - 18.03-1.el7
  	libzen - 0.4.37-1.el7

I can run mediainfo from the command line with no issues.

But when I run it from the application I get the following messages ....

Mediainfo error reading file: 
'./galleries/Videos/Photography_Slideshows/RAW_Movement_2013-08-17.MP4'
Mediainfo error reading file: 
'./galleries/Videos/Photography_Slideshows/RAW_Slideshow_2013-08-08.MP4'
Mediainfo error reading file: 
'./galleries/Videos/Photography_Slideshows/RAW_Sunrise_2013-08-18.MP4'
Mediainfo error reading file: 
'./galleries/Videos/Photography_Slideshows/Slideshow_2013-01-02_DBF_Paint.MP4'

Any ideas? Is it me doing something wrong?

CentOS Linux 7.4.1708
PIWIGO - 2.9.3
PHP70 -  2.3-1.el7

**Comment by jradwan** [comment]
I had a similar issue (after a Ubuntu upgrade which included mediainfo 17.12). Downgrading to 0.7.87 resolved the problem for me.

**Comment by nigel-aves** [comment]
Jeremy,

Thanks for the note. Unfortunately, since 0.7.87 (2016-06-30) over the last 2 years there has been a slew of bug fixes that I now rely on :( .... The silly thing is, it's probably an easy fix, but I'm no programmer and would only make things worse!!

Oh well.  

Nigel.

**Comment by xbgmsharp** [comment]
mediainfo 17.x and mediainfo 18.x are now supported.

**Comment by xbgmsharp** [comment]
Fix with new release 2.9.a

**Comment by nigel-aves** [comment]
I've tested the new code and thumbnails are being created. So thank you ... BUT

None of my videos (that were OK and playing correctly) will now play. If I click the "video" (album page), all I get is a "page with no video on it at all".  i.e top of page / bottom of page but no video frame in the middle.  

On a different site I did have the previous version of VideoJS, (base PWIGO the same and current), and on that site the video is displaying all OK.

I'm not sure the sub-directory setting is working correctly for "video thumbnails". When I ran the code it did create "posters" for all videos in all sub-directories, but only created "video thumbnails" in the first sub-directory found.

If I can provide any further information please let me know.

Nigel.
