### ISSUE TITLE
AVI support?

### ISSUE THREAD

**Issue by tachalainen** [xbgmsharp/piwigo-videojs#121]
Hey!

Using Piwago and your script to an IP Camera that uploads pictures and movies to a server.
The camera is recording AVI files in which is not possible to change to another format.

I’m therefor asking if there’s any possibility at all to get AVI support in this script?

Very much thank you!

 /

**Comment by xbgmsharp** [comment]
AVi is just a file extension, you need to check the video format MPEG2, H264 etc
You can use mediainfo to gather the video details. In any case AVI is more likely not a supported file type by the browser. You will need to convert the video to a supported format by your browser like H264, H265, Webp.
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#issue-content-you-know
