### ISSUE TITLE
RESOLUTION and RESOLUTION_DESC missing in translation files

### ISSUE THREAD

**Issue by jradwan** [xbgmsharp/piwigo-videojs#125]
The translation variables RESOLUTION and RESOLUTION_DESC are used in admin_config.tpl but are not in any of the language files.

**Comment by xbgmsharp** [comment]
True Resolution VideoJS plugin is not implement with all VideoJS player version. I will add a description

**Comment by xbgmsharp** [comment]
Fixed, please test and feedback prior to next release.

**Comment by jradwan** [comment]
Looks good, thanks!
