### ISSUE TITLE
exiftool/ffprobe required for v2.9.a

### ISSUE THREAD

**Issue by jradwan** [xbgmsharp/piwigo-videojs#126]
After upgrading to 2.9.a, the first time I went into the Synchronize tab of the plugin I saw these errors:

```
Notice: Undefined index: ffprobe in /usr/local/piwigo/plugins/piwigo-videojs/include/function_dependencies.php on line 38

Notice: Undefined index: exiftool in /usr/local/piwigo/plugins/piwigo-videojs/include/function_dependencies.php on line 38
```

I was also not able to view videos on my Piwigo site until I installed exiftool (ffprobe was already present on my system) and then filled in the paths to these new tools on the Synchronize tab. Otherwise, when trying to view a video I would get errors like this:

`Exiftool error reading file. Is Exiftool install? Is Exiftool in path?
Is the video accessible & readable, Try to run the command manually.
 -json './upload/2017/02/06/20170206213722-fb9d5b3c.mp4'`

Not sure if this was related to which videojs player version was chosen.

**Comment by xbgmsharp** [comment]
this is not related to which videojs player version was chosen. Should not happen.

**Comment by xbgmsharp** [comment]
Fixed, please test and feedback prior to next release.

**Comment by jradwan** [comment]
Looks good, thanks!
