### ISSUE TITLE
ffprobe with no audio "Undefined offset: 1 in plugins/piwigo-videojs/include/ffprobe.php on line 55"

### ISSUE THREAD

**Issue by ge0rg** [xbgmsharp/piwigo-videojs#128]
When ffprobe is called on a file with only one video stream and no audio stream, there is a warning printed into error.log and into the rendered picture page, from an illegal array offset accesss in ffprobe.php:

```php
if (isset($output['streams'][0]['codec_type']) and $output['streams'][0]['codec_type'] == 'video')
{
        $video = $output['streams'][0];
        $audio = $output['streams'][1]; // <-- this is evil
} else {
        $video = $output['streams'][1]; // <-- this might be too?
        $audio = $output['streams'][0];
}

```

Tested with version 2.9.a of the plugin on Piwigo 2.9.4, running on Debian stable.

**Comment by xbgmsharp** [comment]
Could you send a test file?
In the next version there is no more shell_exec into the rendered picture page.
However the code expect an audio stream. I try to improve it, could you test?

**Comment by xbgmsharp** [comment]
2.9.b release
