### ISSUE TITLE
exiftool not available fault

### ISSUE THREAD

**Issue by erAck** [xbgmsharp/piwigo-videojs#129]
I don't have exiftool installed, on the Synchronise tab the entry is empty and has a green check mark, yet when trying to submit the page (with simulate only) an error message appears:

`
Exiftool error reading file. Is Exiftool install? Is Exiftool in path?
Is the video accessible & readable, Try to run the command manually.
`

VideoJS 2.9.a with Piwigo 2.9.4

**Comment by xbgmsharp** [comment]
exiftool and ffprobe are not require. To my understanding this is already fixed via #126.

**Comment by xbgmsharp** [comment]
2.9.b release

**Comment by erAck** [comment]
Seems ok in 2.9.b, but see #132.
