### ISSUE TITLE
videojs does not use "i" folder for posters & thumbnails

### ISSUE THREAD

**Issue by sock3t** [xbgmsharp/piwigo-videojs#152]
I am running into this error while doing a run of "synchronize";
`Warning: mkdir(): Read-only file system in /var/www/piwigo/plugins/piwigo-videojs/include/function_sync2.php on line 132`

The error message makes sense to me because I put the folder where the videos are located into read-only on purpose. I want to protect these from any changes.

This is where videojs currently tries to put posters & thumbnails:
/var/www/piwigo/_galleries/mygal/sub/folder/_**pwg_representative/**

It would be better to put the posters & thumbnails that videojs creates into a separate folder structure - maybe like the "Generate multiple size images" does:
 /var/www/piwigo/**_data/i/**_galleries/mygal/sub/folder/_

I tried myself and looked into the code of the videojs plugin. Tried to figure what to change to accomplish that but got lost in the vast places where the location of videos vs. their posters & thumbnails is calculated.

It would be great to get this changed. Or maybe I overlooked some global variable to change the location for posters & thumbnails?

Thanks

**Comment by bobribbon** [comment]
You can try this:
https://github.com/xbgmsharp/piwigo-videojs/issues/97?_pjax=%23js-repo-pjax-container#issuecomment-528496644

**Comment by sock3t** [comment]
My own attempts to hack the path and what was observed in #97 shows that this will likely never work. Piwigo itself has this path hardcoded in countless spots in the code and requires all plugins / extensions to comply with that - which is fair.

The use-case to have the image folders / galeries read only is somewhat exotic.

I solved this for me by creating symlinks:
/var/www/piwigo/galleries/mygal/sub/folder/pwg_representative/ -> /var/www/piwigo/_data/i/galleries/mygal/sub/folder/pwg_representative

**Comment by corsac-s** [comment]
> My own attempts to hack the path and what was observed in #97 shows that this will likely never work. Piwigo itself has this path hardcoded in countless spots in the code and requires all plugins / extensions to comply with that - which is fair.

I find it a bit strange considering that Piwigo already puts some local stuff inside `_data`. Maybe it'd just be a matter of asking on the Piwigo issue tracker?
 
> The use-case to have the image folders / galeries read only is somewhat exotic.

I don't think that's really true and in any case, it's already supported for standard images so…

> 
> I solved this for me by creating symlinks: /var/www/piwigo/galleries/mygal/sub/folder/pwg_representative/ -> /var/www/piwigo/_data/i/galleries/mygal/sub/folder/pwg_representative

Unfortunately that doesn't really scale (you need to manually / scriptically create the folder for every new album).

**Comment by RenaeMacLeod** [comment]
Same here WRT read only access to pictures. I tried generating the files with the same name and putting them in 'pwg_representative' sub directory, then using the standard Piwigo sync to add them. Also tried JPG and PNG extensions.
