### ISSUE TITLE
Issues with swf files

### ISSUE THREAD

**Issue by abrenoch** [xbgmsharp/piwigo-videojs#29]
I realize this plugin doe not have support for swf files, but there seems to be something causing an incompatibility with them.

I'm using the 'charlies content' plugin, which supports swf files, but if I run videojs alongside it then problems happen.. The error I'm seeing is:

    Notice: Undefined index: swf in /var/www/clients/client1/web3/web/plugins/piwigo-videojs/main.inc.php on line 359

If I disable videojs, everything seems to work fine.. So I'm wondering, why is videojs attempting to read the swf files despite them not being supported with it? Is there a way to get around this? I'm not entirely sure where videojs is being told to parse the swf files.. But I may end up digging into this myself if nobody has any tips for me!

**Comment by xbgmsharp** [comment]
Fixed and release, closing
