### ISSUE TITLE
srcnotfound - Bad path with piwigo in subdir

### ISSUE THREAD

**Issue by jcz1** [xbgmsharp/piwigo-videojs#46]
My piwigo installation is in foto subdir. Full path is www.some.com/foto/.

When i uploaded mp4 video, i see thumbnail and i am able to download mp4 file. But player shows srcnotfound error message even after synchronization. In apache i found this error:

File does not exist: /data/www/www.some.com/upload

... with missing /foto/ directory. I created symlink:

/data/www/www.some.com/upload -> foto/upload

and it works. Probably there is a bug in path selection.

**Comment by xbgmsharp** [comment]
Thanks for the feedback.
Upload video play correctly for me. Please send the process to reproduce the issue.
Did you attach the upload to a virtual album? to a sub album?

**Comment by jcz1** [comment]
maybe problem with "clean urls"?

from src (public part of gallery):
<a href="../../../upload/2015/02/03/20150213154455-3919abaa.mp4...

and gallery-video URL:
http://myweb.tld/gallery/picture/9251-moviename/category/675-subalbumname

my config:
$conf['question_mark_in_urls'] = false;
$conf['php_extension_in_urls'] = false;
$conf['category_url_style'] = 'id-name';
$conf['picture_url_style'] = 'id-file';

**Comment by jcz1** [comment]
btw it is in subalbum in virtual album

**Comment by xbgmsharp** [comment]
Thanks, I will check on subalbum in virtual album.

**Comment by xbgmsharp** [comment]
I try adding the following scenario.
With default config set:
 * a manually import video in a subalbum of an album and it works fine.
 * a upload video in a virtual subalbum of a virtual album and it works fine.

With your config set (got an hard time with .htaccess):
 * a manually import video in a subalbum of an album and it does not works. Same error.
 * a upload video in a virtual subalbum of a virtual album and it does not works. Same error.
 * a manually import video in a album and it does not works. Same error.
 * a upload video in a virtual album and it does not works. Same error.

Now that I'm able to reproduce the issue, I will try to find a work around.
The fun part if that the poster get display fine.

**Comment by jcz1** [comment]
Thx for tests. What about URL with "$piwigoroot/upload/..." instead of "../../.." path? I don't know about  $piwigoroot but probably there is some internal variable, because there is configuration to override.

**Comment by xbgmsharp** [comment]
The patch are generated via ``get_gallery_home_url()`` and ``get_absolute_root_url()``.
Those are PWG function.

I commit a fixed.
Please test and feedback.

**Comment by jcz1** [comment]
It's ok now. Thanks for you work.
