### ISSUE TITLE
avconv support on debian jessie

### ISSUE THREAD

**Issue by emja** [xbgmsharp/piwigo-videojs#51]
ffmpeg is not available for debisn jessie, it instead has been replaced by avconv.

I have configured piwigo to use avconv, however posters do not work properly. Presumably the syntax is not similar enough between ffmpeg and avconv.

**Comment by emja** [comment]
oops, only just now found this: http://piwigo.org/forum/viewtopic.php?pid=158049

The forum thread implies my problem is not avconv vs ffmpeg, but possibly elsewhere.

**Comment by xbgmsharp** [comment]
What do you refer as "posters do not work properly".
As specify in the forum thread, I explained that according to my test it works fine.
Also I use very basic feature of ffmpeg and there is no difference between the two.

**Comment by emja** [comment]
I get only an empty black image. I've since run the command manually (same as in the plugin) and get the same result.

If it helps, here's the output of 'avconv -version':
avconv version 11.2-6:11.2-1, Copyright (c) 2000-2014 the Libav developers
  built on Jan 17 2015 21:51:46 with gcc 4.9.2 (Debian 4.9.2-9)
avconv 11.2-6:11.2-1
libavutil     54.  3. 0 / 54.  3. 0
libavcodec    56.  1. 0 / 56.  1. 0
libavformat   56.  1. 0 / 56.  1. 0
libavdevice   55.  0. 0 / 55.  0. 0
libavfilter    5.  0. 0 /  5.  0. 0
libavresample  2.  1. 0 /  2.  1. 0
libswscale     3.  0. 0 /  3.  0. 0

**Comment by xbgmsharp** [comment]
Do you have any error when running the command manually?
Can you send the full output? I am still running on Wheezy.
Also as per documentation, depending on the input/output format used FFmpeg might required additional library please refer to the wiki documentation.
To support all video format conversion, you can run this command, on Debian 7 (Wheezy):
```
# apt-get install libfaad2 libx264-123 libvorbis0a libvorbisenc2 libvorbisfile3 libvpx1 libxvidcore4
```

**Comment by emja** [comment]
I get no error when running the command manually. The packages you've listed are all installed, except libx264-123. libx264-123 is unavailable, however there is libx264-142, which is installed.

Output from the command:
$ /usr/bin/avconv -itsoffset -2 -i 'blah.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -y 'blah.jpg'
avconv version 11.2-6:11.2-1, Copyright (c) 2000-2014 the Libav developers
  built on Jan 17 2015 21:51:46 with gcc 4.9.2 (Debian 4.9.2-9)
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'blah.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf53.21.1
  Duration: 00:00:14.08, start: 0.000000, bitrate: 10736 kb/s
    Stream #0.0(und): Video: h264 (High), yuv420p, 1280x720 [PAR 1:1 DAR 16:9], 10685 kb/s, 25 fps, 25 tbn, 50 tbc (default)
    Stream #0.1(und): Audio: aac, 44100 Hz, stereo, fltp, 45 kb/s (default)
Output #0, rawvideo, to 'blah.jpg':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf56.1.0
    Stream #0.0(und): Video: mjpeg, yuvj420p, 1280x720 [PAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 25 tbn, 25 tbc (default)
    Metadata:
      encoder         : Lavc56.1.0 mjpeg
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mjpeg (native))
Press ctrl-c to stop encoding
frame=    1 fps=  0 q=2.0 Lsize=      15kB time=10000000000.00 bitrate=   0.0kbits/s    
video:15kB audio:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%

btw, if instead I run the following, it seems to work:
/usr/bin/avconv -ss 2 -i 'blah.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -y 'blah.jpg'

**Comment by xbgmsharp** [comment]
According to [avconv Documentation](https://libav.org/avconv.html), the option ``‘-itsoffset offset (input)’`` is supported. The option ``‘-ss position (input/output)’`` is the same as ``‘itsoffset’``.

>‘-itsoffset offset (input)’
>
>  Set the input time offset in seconds. [-]hh:mm:ss[.xxx] syntax is also supported. The offset is added 
> to the timestamps of the input files. Specifying a positive offset means that the corresponding  streams are delayed by offset seconds.

Maybe the ``-`` negative offset is the issue.
What if you run:
```
$ /usr/bin/avconv -itsoffset 2 -i 'blah.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -y 'blah.jpg'
```

**Comment by emja** [comment]
Nope, same result.

**Comment by emja** [comment]
More testing. The problem is not explicitly a black empty image but rather that avconv is exporting only the *first* frame, which just happened to be normally black. I've edited a test video to remove the fade-in and fade-out, and I can see I consistently get only the first frame. Adjusting the offset makes no difference.

**Comment by emja** [comment]
This may help: https://lists.gnu.org/archive/html/ranger-users/2013-07/msg00044.html

**Comment by xbgmsharp** [comment]
Wow thanks for the tips.
 I committed a change 250ce68 to reflect the conversation.

**Comment by emja** [comment]
Beaut. Your patch has been installed and successfully tested.

Many thanks for your help with this one!

**Comment by xbgmsharp** [comment]
Glad it works.
Thanks for the feedback.

**Comment by xbgmsharp** [comment]
I have change some option for ffmpeg and would like to ensure it is working fine with avconv.
Would you be able to feedback on issue #52?

**Comment by emja** [comment]
Sure. I'll be able to get to testing it within the next 48hrs.

**Comment by emja** [comment]
This has been installed and tested, and seems to work fine.

**Comment by xbgmsharp** [comment]
Great, good news! Thanks for the feedback.
