### ISSUE TITLE
Distorted thumbnails

### ISSUE THREAD

**Issue by xbgmsharp** [xbgmsharp/piwigo-videojs#52]
Thanks to @photonensammler for reporting this issue

The thumbnails are force to a specific size and does not respect the aspect ratio.
Therefor is does create distort thumbnails.

Interesting reading:
https://trac.ffmpeg.org/wiki/Scaling%20%28resizing%29%20with%20ffmpeg
http://stackoverflow.com/questions/8218363/maintaining-ffmpeg-aspect-ratio

**Comment by xbgmsharp** [comment]
What if...
It takes output width (ow), divides it by aspect ratio (a), truncates digits after decimal point.
```
                $scale = "scale='".$thumb_witdh[0].":trunc(ow/a)'";
```
For example with a thumbnail width of 120px and a video aspect ratio of 4:3  (640px*480px) we have an height of 89px.
For example with a thumbnail width of 120px and a video aspect ratio of 16:9 (1280px*720px) we have an height of 66px.

**Comment by photonensammler** [comment]
A good idea, ffmpeg working left to.
But if someone mobile phone has to be held verticaly and a he has a video with 720 x 1280 (9:16) , we have a thumbnail height of 2px.

When the width of the video is greater than the height:
<code>
$scale = "scale='".$thumb_witdh[0].":trunc(ow/a)'";
</code>

When the height of the video is greater than the width:
<code>
$scale = "scale='".trunc(ow/a):".$thumb_height[0]'";
</code>

So we have a thumbnail height of 213px.

**Comment by xbgmsharp** [comment]
For a thumbnail width of 120px.
- A video aspect ratio of 4:3 (640x480)px we have an thumbnail height of 89px. (120x89)px
- A video aspect ratio of 16:9 (1280x720)px we have an thumbnail height of 66px. (120x66)px
- A vertical video aspect ratio of 16:9 (568x320)px we have an thumbnail height of 66px. (120x66)px

If the video provide the rotation parameter then the thumbnails are rotate accordingly.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/main.inc.php#L296

If the video provide the rotation parameter then the video is rotate accordingly.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/main.inc.php#L325
It does require the videojs-rotatezoom plugin to be activated.
https://github.com/xbgmsharp/piwigo-videojs/wiki/Configuration#videojs-plugin

**Comment by xbgmsharp** [comment]
> Great!!! now also agrees the aspect ratio of thumbnails :-)
