### ISSUE TITLE
Is it possible to use native html5 player

### ISSUE THREAD

**Issue by jeroenpraat** [xbgmsharp/piwigo-videojs#56]
Hi,

I was wondering if it's possible to use the native html5 video player? Firefox and Chrome have a very decent html5 video player that works (for me) smoother as VideoJS. That said, I do like the thumbnail generation of this Piwigo plugin.

**Comment by xbgmsharp** [comment]
Hello,

Technically it believe it is possible. It could be done as an option.
The main problem is you are limited to the file supported by your Operating System / Browser combination. http://www.videojs.com/html5-video-support/
Further testing and integration need to be done.

**Comment by xbgmsharp** [comment]
I added a new template for using the default HTML5 player included in the browser.
Please note that you are limited to the video file supported by your Operating System / Browser combination. http://www.videojs.com/html5-video-support/

To test it, edit the file `main.inc.php` at line 376 and replace ``"/template/vjs-player.tpl"`` by ``"/template/html5-player.tpl``.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/main.inc.php#L376

If it works correctly or as expected, I will add an option in the configuration menu.

Please test and feedback.

**Comment by jeroenpraat** [comment]
First thanks for your work. It works in Chromium/Chrome, but not in my beloved Firefox (desktop). I know that it must work, because when I load the video directly it works flawlessly.

It only shows the thumbnail with the HTML5 videocontrols at the bottom, but clicking play doesn't do anything and a right click on the video content doesn't show the expected HTML5 video options.

**Comment by jeroenpraat** [comment]
Oh BTW, I see it loads the video file on the background (download goes up, when closing the tab download rate goes back to 0).

**Comment by jeroenpraat** [comment]
How to send you the video?

**Comment by xbgmsharp** [comment]
Email 
My email is everywhere in the source code

**Comment by xbgmsharp** [comment]
Send a sample video by email or via any share file platform.

**Comment by xbgmsharp** [comment]
I try your video using both template the HTML5 and VJS player on Firefox.
No issue at all.
![screen shot 2015-04-05 at 10 42 48 am](https://cloud.githubusercontent.com/assets/1498985/6996442/ed713fec-db80-11e4-8268-f02d75331b3d.png)

**Comment by xbgmsharp** [comment]
Closing the issue, publish on new release v2.8.a
