### ISSUE TITLE
Thumbnails with movie frame not generated at upload

### ISSUE THREAD

**Issue by fcoiffie** [xbgmsharp/piwigo-videojs#57]
When I upload a new video, the corresponding thumbnail is generated.
But not with a movie frame.

So I have to resynchronize the videos to get correct thumbnails.
Is there a solution to automatically generate thumbnails with movie frame ?

**Comment by xbgmsharp** [comment]
Hello,
That is correct and the normal behavior.
The PWG team did not include all the feature (movie frame and time selection) I have implemented on the synchronize page for VideoJS.
It also support less videos file format, see http://piwigo.org/bugs/view.php?id=3217
There is thread on rewriting the upload system, you are more likely welcome to join and give your input, see http://piwigo.org/forum/viewtopic.php?id=24845

**Comment by xbgmsharp** [comment]
Closing nothing that I can do. Those are 2 different process, you must sync on the synchronize page for VideoJS.
