### ISSUE TITLE
adding support for mov files

### ISSUE THREAD

**Issue by eephyne** [xbgmsharp/piwigo-videojs#61]
Hello

I wanted to know if the support for other videos files is something planned or not ?

I hate transcoding files because of the quality loss and the cpu time.

if this is something simple to achieve, could you give me a direction so I can do it myself (if this is not something you want to add)

thanks

**Comment by xbgmsharp** [comment]
Hello,

Unfortunately, it is not my decision.
VideoJS is a HTML5 video player. 
It does provide a improve design and extension support from the default browser player.
The video file supported depend on the browser, refer to http://www.videojs.com/html5-video-support/ and http://blog.zencoder.com/2013/09/13/what-formats-do-i-need-for-html5-video/

The main goal is not load Flash, which does support more format but is proprietary and heavy.

MOV format is very similar to MP4 and can be transcode without any quality loos.
Handbrake is a good start, https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#issue-content-you-know

Sorry

**Comment by eephyne** [comment]
I  understand and agree the policy of do not load flash evil memory eater (among others things) but in my browser I can read mov natively.

**Comment by xbgmsharp** [comment]
You probably don't read then natively, you more likely have a plugin install.
