### ISSUE TITLE
Wrong URLs for video files

### ISSUE THREAD

**Issue by CChiappa** [xbgmsharp/piwigo-videojs#63]
My piwigo site is under /piwigo, with galleries as a subdirectory (ie /piwigo/galleries).  Everything works fine, but videos are loaded from /galleries rather than /piwigo/galleries.  They work fine if I make a symlink, but it seems like something isn't set up right.  What might be happening for the incorrect URLs to be generated?  Here are two lines from the access.log showing a working access via /piwigo followed by the movie getting loaded from /galleries:
1.2.3.4 - - [20/Jul/2015:19:37:45 -0400] "GET /piwigo/picture/20150228_1328
57_Something/category/665-28feb2015 HTTP/1.1" 200 5162 "http://www.host.com/piw
igo/picture/20150228_132750_Something/category/665-28feb2015" "Mozilla/5.0 (X11; L
inux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.1.0"
1.2.3.4 - - [20/Jul/2015:19:37:44 -0400] "GET /galleries/Someone/SomethingFeb20
15/28Feb2015/20150228_132750_Something.mp4 HTTP/1.1" 206 67105823 "http://www.host.com/piwigo/picture/20150228_132750_Something/category/665-28feb2015" "Mozilla/
5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.1.0"

**Comment by xbgmsharp** [comment]
Could you please install the latest github version and re-test. https://github.com/xbgmsharp/piwigo-videojs#installation
Does it happen with all the video? I mean do you have multiple source for the same video?
Do you have any special settings in your PWG configuration.
Could you provide access to you PWG privately, so I can check.
My gallerie use ``/piwigo/galleries`` and I have no issue.

**Comment by CChiappa** [comment]
Huh, perhaps removing and reinstalling fixed something since it works fine now:
1.2.3.4 - - [23/Jul/2015:11:33:47 -0400] "GET /piwigo/galleries/Someone/Something-10May2015/20150510_141240_Something.mp4 HTTP/1.1" 206 126620372 "http://www.host.com/piwigo/picture/20150510_141240_Something/category/670-something_10_may_2015" "Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0 Iceweasel/39.0"
Sorry about the bother!
