### ISSUE TITLE
video does not play...

### ISSUE THREAD

**Issue by MisterEffiks** [xbgmsharp/piwigo-videojs#66]
Hi,

i've migrated all my photos and videos from gallery3, but no video ist playing in any browser on any system with the videojs-plugin.
All required packages are installed (avconv, ffmpeg, mediainfo...)
Metadata are OK, posters are generated, but no play.
Any hints to get this work?

https://richterfelix.de/fotoalbum_neu/index.php?/category/4

I've also used the big_buck_bunny.mp4 (test.mp4) (with new folder, uploaded as new), but it's not playing.

Thanks,
MisterEffiks

![bildschirmfoto 2015-08-20 um 13 58 04](https://cloud.githubusercontent.com/assets/13886398/9382723/87c2b05c-4743-11e5-89f1-eb638c2d0343.png)

**Comment by xbgmsharp** [comment]
If you display the console, you will see the following message from videojs:
```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The video could not be loaded, either because the server or network failed or because the format is not supported. Object { code: 4, message: "The video could not be loaded, eith…" } 
```
Which format if you video? I don't refer to the extension. Use the photo-edit page to see the codec.
Please refer to the wiki for more details, https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#issue-content-you-know

**Comment by xbgmsharp** [comment]
In fact the problem is even easier, the file does not exist.
```
HTTP load failed with status 404. Load of media resource https://richterfelix.de/fotoalbum_neu/galleries/test/astra_tid_test.m4v failed.
```
Which version of the plugin do you use?
Please ensure you use the latest github version. https://github.com/xbgmsharp/piwigo-videojs#installation

**Comment by MisterEffiks** [comment]
OK, thanks for the hint... it was a redirect-rule in .htaccess, which was in the subfolders migrated from gallery3... now it works :)

Best wishes,
MisterEffiks
