### ISSUE TITLE
Why is mediainfo 0.7.64 required?

### ISSUE THREAD

**Issue by plegall** [xbgmsharp/piwigo-videojs#74]
On some servers I'm still running Debian 7 (which is still maintained) and I have only mediainfo 0.7.58. Why is version 0.7.64 required and is the error message really necessary?

**Comment by xbgmsharp** [comment]
MediaInfo change is output format by default between version 0.7.5x and 0.7.6x
In addition a version of 0.7.7x have XML output broken.
There is a check of minimum version requirement.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L45

You can install a newer version on Debian 7 following the install instruction available on the wiki.
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#external-tools

**Comment by plegall** [comment]
OK, I'll try that. So it means piwigo-videojs is not able to parse the XML output of my version of mediainfo, however I now have the appropriate width/height for my webm video.

**Comment by xbgmsharp** [comment]
Width and Height can be retrieve via the ``getimages()`` function where the metadata can only be retrieve using MediaInfo. However it is does not work on Windows System, there is a bug open for it.
Using the photo edit page for a video, you should be able to see all the gather information related to your video.
