### ISSUE TITLE
Warning: Division by zero in /www/htdocs/html/plugins/piwigo-videojs/main.inc.php on line 323

### ISSUE THREAD

**Issue by SSedl** [xbgmsharp/piwigo-videojs#76]
```
Warning: Division by zero in /www/htdocs/html/plugins/piwigo-videojs/main.inc.php on line 323
```
What could be the problem?

**Comment by SSedl** [comment]
What could be the problem?

**Comment by SSedl** [comment]
"Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/html/plugins/piwigo-videojs/main.inc.php:323) in /www/htdocs/html/include/page_header.php on line 101"       That's another warning I get

**Comment by xbgmsharp** [comment]
Did you sync you image prior?  It sound similar to issue #50.
Could you try using the latest Github version?
https://github.com/xbgmsharp/piwigo-videojs#installation

**Comment by xbgmsharp** [comment]
Please ensure you sync the file using PWG first then by VideoJS plugin.
You can check in the mysql database you do have a height and width set.
Please try with the latest release v2.8.a
