### ISSUE TITLE
Automatic creation of poster

### ISSUE THREAD

**Issue by masakik** [xbgmsharp/piwigo-videojs#78]
Hi, thanks for this great plugin. When I upload a video to any album using html5 uploader, the poster is created automatically or need to be done in plugin sync tab?

**Comment by xbgmsharp** [comment]
When you upload a Video PWG will create a poster.
If you want to use the poster feature of the plugin you need to run a sync.
https://github.com/xbgmsharp/piwigo-videojs/wiki/Synchronize

**Comment by masakik** [comment]
Thanks for reply.
