### ISSUE TITLE
Issue with Creating Posters

### ISSUE THREAD

**Issue by BaceWindu37** [xbgmsharp/piwigo-videojs#79]
I am having an issue with the automatic Poster maker.  When I click on synchronize in the VideoJS plugin tab there is no error messages and it says that it generated the Posters.  However, when I go to the pwg_representative folder it is empty.  Is this a permissions issue?  I am unsure how to proceed in solving this issue.

Thanks

**Comment by xbgmsharp** [comment]
There is a few step to do.
After reading the wiki, https://github.com/xbgmsharp/piwigo-videojs/wiki/Synchronize#poster

Are you able to create the poster using the command line?
https://github.com/xbgmsharp/piwigo-videojs/wiki/Synchronize#poster-generation

If it works, then check your webserver log. you more likely have a PHP limitation. This plugin use the PHP system() and shell_exec() call.
https://github.com/xbgmsharp/piwigo-videojs/wiki/How-to-add-videos#no-im-not-root

**Comment by BaceWindu37** [comment]
I was able to make a poster when I did it manually, but am unable to do it when I click on synchronize.  I checked what I think may be the webserver log and it had multiple lines that said File Read Error.  What should I do to resolve this issue?

Thank you for the quick response and helping me out. :)

**Comment by xbgmsharp** [comment]
Please provide the exact error message from your webserver.

**Comment by xbgmsharp** [comment]
Closing no update, more likely a configuration issue or permission issue.
