### ISSUE TITLE
How to disable thumb creation;  Where can I find the ffmpeg calls?

### ISSUE THREAD

**Issue by geckotechcr** [xbgmsharp/piwigo-videojs#80]
Hello,  this plugin is great.  It allows us to uploade small MP4 files and have them treated just like a normal photo.

I am trying to find out where you reference the ffmpeg (make the calls) so I can disable (comment out) the thumbnail creation as we will not need thumbnails and need to conserve the host processing bandwidth.

Also, we will be uploading MP4s that range from 5 seconds to 30 seconds. Ideally we would like the poster to be created from the halfway mark (50% into) each MP4.   Is this possible?  If not we will simply set the ffmpeg to pull poster from the 2nd second .

thank you for a great plugin and your support.
Sean

**Comment by xbgmsharp** [comment]
The upload process is manage by PWG core. You can not select the second for the porter generation on upload.
However using the plugin, you specify the second for the porter generation as well if you want to create a poster.
https://github.com/xbgmsharp/piwigo-videojs/wiki/Synchronize

**Comment by geckotechcr** [comment]
Thank you for the reply.

On PWG: Admin.Plugins.videojs I am not able to find the options to change
this setting...

We had downloaded and installed your plugin from github, and once installed
it shows only this tab:

Can you tell me how i can disable ALL thumb generation and change the
second for poster creation during Synchronization?

Thanks again for your support.
Sean


   - Configuration
   <http://geckophoto.geckointernational.com/admin.php?page=plugin&section=piwigo-videojs%2Fadmin%2Fadmin.php&tab=config>

VideoJS Plugin [Configuration]
This plugin add the open source HTML5 video player VideoJS
<http://www.videojs.com/>.

Refer to the plugin documentation
<https://github.com/xbgmsharp/piwigo-videojs/wiki> for additional
information. Create an issue
<https://github.com/xbgmsharp/piwigo-videojs/issues> for support, or
feedback, or feature request.
Statistics

   - 11326 videos in your gallery
   - 10909 videos with poster in your gallery

HTML5 video tag settings

   - Preload :  Auto None
   The preload attribute informs the browser whether or not the video data
   should begin downloading as soon as the video tag is loaded.
   - Controls : Yes  No
   The controls option sets whether or not the player has controls that the
   user can interact with
   - Autoplay : Yes  No
   If autoplay is true, the video will start playing as soon as the page is
   loaded (without any interaction from the user). NOT SUPPORTED BY APPLE iOS
   DEVICES.
   - Loop : Yes  No
   The loop attribute causes the video to start over as soon as it ends.
   - Volume : 1
   The volume option sets the volume level. 0 is off (muted), 1.0 is all
   the way up, 0.5 is half way.
   - Language :  en ja ca nl de tr bg ru ko zh-TW uk pt-BR vi zh es ar hu
   zh-CN it fr cs
   Select the player language.

Plugin settings

   - Skin :  default bluebox redtube
   Select the style you want to apply to the player or create your own skin
   <http://designer.videojs.com/>.
   - Custom CSS :
   Custom CSS to copy paste from the VideoJS website
   <http://www.videojs.com/>.
   - Max Height :  EDTV: (720x480) ie: 480p EDTV: (720×576) ie: 576p HDReady:
   (1280x720) ie: 720p FullHD: (1920x1080) ie: 1080p 4k UHDTV: (3840×2160)
   ie: 2160p 8k UHDTV: (7680×4320) ie: 4320p
   The max height attribute sets the maximum display height of the video.
   If the video height is bigger than max height, it will downscale the video
   size to max height.
   - Upscale : Yes  No
   If the video height is smaller than max height, it will upscale the
   video size to max height.

VideoJS plugins

   - ZoomRotate : Yes  No
   Rotate and zoom a video if applicable, use the rotation metadata.
   - Thumbnails : Yes  No
   Displays thumbnail images over the progress bar.
   - Watermark : Yes  No
   Displays watermark over the video.

**Comment by xbgmsharp** [comment]
There is 2 tabs, Configuration &  Synchronise. You copy paste the  Configuration tab.
Again the Synchronise only works after the upload.
Those are 2 separated process.
You should read the documentation.

For the PWG core feature, you need to ask on their forum.

**Comment by xbgmsharp** [comment]
You can disable ALL thumb generation and change the second for poster creation during Synchronization, you need untick ``Create a thumbnail at every seconds``. 
It will prevent the system to create the thumbnail.
If you untick ``Create a poster at position in second`` you will disable poster creation.
