### ISSUE TITLE
only black screenshots

### ISSUE THREAD

**Issue by flth** [xbgmsharp/piwigo-videojs#81]
all videos starting with a black screen but I've set the "Create a poster at position in second:" to 4 or even 15 (seconds), the screenshots are always black.
Using avconv under Ubuntu 14.04, what's wrong? What do we need to track the problem?

**Comment by xbgmsharp** [comment]
While using the Synchronize tab, you can read the documentation.
https://github.com/xbgmsharp/piwigo-videojs/wiki/Synchronize#poster-generation
There can be a number of reason. Try to first generate the poster manually.

**Comment by flth** [comment]
it seems the -ss parameter is not set, videoJS is executing command like e.g.

/usr/bin/avconv -itsoffset -4 -i './galleries/MOVIES/videoX/videoX.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -y './galleries/MOVIES/videoX/pwg_representative/videoX.jpg'

When I pass -ss parameter (like -ss 15) manually on this command, it creates a screenshot at 15s.
Why is that missing or why is -itsoffset not doing the job and how to change it?

**Comment by xbgmsharp** [comment]
The ``-ss`` parameters is present.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/function_sync2.php#L149
You might want to update to the latest github version.

**Comment by flth** [comment]
thanks that helped, changed the command to my needs :)

Good support!
