### ISSUE TITLE
Poster creation failed (but solved)

### ISSUE THREAD

**Issue by kuzco1** [xbgmsharp/piwigo-videojs#84]
I have some strange issues with the Piwigo 2.8.1 (on Windows) and VideoJS 2.7a.

(1) When using mediainfo 0.7.76 or greater I do get the following error message when creating poster, etc:

Mediainfo error reading file
Is MediaInfo install?
Is MediaInfo in path?
Is the video accessible & readable
Try to run the command manually.
mediainfo --Full --Output=XML --Language=raw './galerien/Ausfluege_und_Events/2016/05_15_SuperFly_Ruhr/2016_05_15_14_50_14_P5150700.mp4'

So, VideoJS does not recognize mediainfo 0.7.76 greater

(2) When using mediainfo 0.7.75 I do get the following error:

Mediainfo error reading file:
'./galerien/Ausfluege_und_Events/2016/05_15_SuperFly_Ruhr/2016_05_15_14_50_14_P5150700.mp4'
Error poster running ffmpeg, try it manually:
ffmpeg -itsoffset -4 -i './galerien/Ausfluege_und_Events/2016/05_15_SuperFly_Ruhr/2016_05_15_14_50_14_P5150700.mp4' -vcodec mjpeg -vframes 1 -an -f rawvideo -y './galerien/Ausfluege_und_Events/2016/05_15_SuperFly_Ruhr/pwg_representative/2016_05_15_14_50_14_P5150700.jpg'

So, it seems that I do have again the same error message I had previously in #42 (https://github.com/xbgmsharp/piwigo-videojs/issues/42)
So, I changed again in include/function_sync2.php:
Line 148 from:
$ffmpeg = $sync_options['ffmpeg'] ." -itsoffset -".$sync_options['postersec']." -i '".$in."' -vcodec mjpeg -vframes 1 -an -f rawvideo -y '".$out. "'";
to
$ffmpeg = $sync_options['ffmpeg'] ." -itsoffset -".$sync_options['postersec']." -i ".$in." -vcodec mjpeg -vframes 1 -an -f rawvideo -y ".$out;
    
line 151 from:
$ffmpeg = $sync_options['ffmpeg'] ." -itsoffset -".$sync_options['postersec']." -i '".$in."' -vcodec png -vframes 1 -an -f rawvideo -y '".$out. "'";
to
$ffmpeg = $sync_options['ffmpeg'] ." -itsoffset -".$sync_options['postersec']." -i ".$in." -vcodec png -vframes 1 -an -f rawvideo -y '".$out;

And after checking where the mediainfo will be checked (/includes/mediainfo.php), I changed line 32 from:
$output = shell_exec($sync_options['mediainfo'] ." --Full --Output=XML --Language=raw '". $filename."'");
to
$output = shell_exec($sync_options['mediainfo'] ." --Full --Output=XML --Language=raw ". $filename);

This solved the problem on Windows, I am not sure that these chnages are also working on Linux !
Please verify.

**Comment by xbgmsharp** [comment]
Thanks for the feedback, my fault for not making a proper release but it is present.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/mediainfo.php#L32

**Comment by xbgmsharp** [comment]
Closing the issue, fix on new release v2.8.a
