### ISSUE TITLE
can't select nor unselect directories in "reduce to single existing album" while synchronising

### ISSUE THREAD

**Issue by patmans** [xbgmsharp/piwigo-videojs#85]
Hi -

While synchronizing, is there some way to *not* select any directories?

I've tried control-clicking, clearing my cookies, logging in and out, but no matter what when I go into the synchronize tab, it has the same directory selected that I last synchronized.

With the main synchronization tab, it never saves my selection - that's also not so great, as you can't search nor easily find a specific directory when there are hundreds of choices, but I can live with it.

I'm on a linux distro, Fedora 23 with KDE, using Firefox to piwigo 2.8.1 with piwigo-videojs via git at 254383c.

Thanks ...

**Comment by xbgmsharp** [comment]
It is correct the main synchronization tab,never saves my selection. It reset to default.
The album is selection is the same for all piwigo, eg: Tools -> Synchronise.

If you have the same issue, then it is a PWG issue.

**Comment by patmans** [comment]
The main (non piwigo-videojs) synchronization tab never saves my selection, but the piwigo-videojs synchronization tab *always* saves my selection, and there is no way I can find to *not* select anything :-(

This is quite annoying, as it means I can't just sync all of my videos across all folders. I have 12 top level folders, so I can just sync 12 times.

**Comment by xbgmsharp** [comment]
By default there is no restriction on the album you sync against. It does run over all folders by default.
Do you refer to ``reduce to single existing album`` or to other settings?

**Comment by xbgmsharp** [comment]
I was able to reproduce the issue. There must be a change from PWG2.8, will look into it.

**Comment by xbgmsharp** [comment]
I commit a fix. Would be great if you could test and report.
Thanks

**Comment by patmans** [comment]
Thanks, the fix worked for me!
