### ISSUE TITLE
Video playback broken when FFmpeg and MediaInfo plugins are not available, related to exif data display

### ISSUE THREAD

**Issue by digibirdtrek** [xbgmsharp/piwigo-videojs#87]
Recently upgraded to piwigo-videojs version 2.8.a  Running Piwigo version 2.8.1  

Upon doing so video playback was broken due to required FFmpeg and MediaInfo missing.  It appears something changed with the new version where these plugins are now required even for playback.  Even after disabling all options in the videojs config settings that would use these plugins, when accessing the video it gets kicked to an error page.  Tried all versions of the player with the same result, kicked to error page on video loading.

I finally traced this down to main config variables related to exif display.  Disabling configuration  variable temporarily solves the problem however this also disables all exif data display.

`$conf['show_exif']=false`

I have a customized exif display using the related config variable array which has remained unchanged since upgrade.

`$conf['show_exif_fields'] = array(
  'Make',
  'FNumber',
  'ExposureTime',
  'ISOSpeedRatings',
  'FocalLength',
  'DateTimeOriginal',  
  'Artist',
  'Copyright'
  );`

I have not played around with the array elements to determine if any specific one is causing the call to the missing plugin, presumably MediaInfo. 

Not sure what the best way to resolve the exif display issue as I would like to retain that ability for photos.

**Comment by xbgmsharp** [comment]
FFmpeg and MediaInfo should not be require for playback. However MediaInfo is need to display video metadata but it only run when request with the extra parameter, eg: ``1&metadata``.

If I understand correctly, even so your ``'show_exif_fields'`` does not include any video metadata, It still run. Could you try to Remove the ``Make`` field.

I will add an option to display the Metadata if active.

**Comment by digibirdtrek** [comment]
Tried removing the "make" field, got error.  Then tried removing everything other than the "make" field still got error.  Then tried removing all elements from the array and still got error.  Seems as soon as the "show_exif" variable is set to true it will look for the MediaInfo plugin.

**Comment by xbgmsharp** [comment]
I confirm, I made an option available via commit e108dd4d372c7439da256e35e5240f1899c3c6f9.
If You could test and report it would be great.
Ideally the metadata information are store in the database to avoid running MediaInfo.

**Comment by digibirdtrek** [comment]
Tested and that did the trick.  Note, needed to save the configuration in admin before the changes worked.

**Comment by xbgmsharp** [comment]
Great, Thanks, I will release the new version soon.
Correct you needed to save the configuration in admin before the changes worked. The default value is true.
