### ISSUE TITLE
ffmpeg error "deprecated pixel format used, make sure you did set range correctly"

### ISSUE THREAD

**Issue by patmans** [xbgmsharp/piwigo-videojs#88]
Hi -

ffmpeg is failing sometimes on me when trying to create the "poster" (i.e. thumbnail) while syncing.

Errors seen while syncing are:

Error poster running ffmpeg, try it manually:
```
ffmpeg -ss 4 -i "./galleries/200_house/96485_bird_calls_at_home/96485.mp4" -vcodec mjpeg -vframes 1 -an -f rawvideo -y "./galleries/200_house/96485_bird_calls_at_home/pwg_representative/96485.jpg"
```
Running it manually, I see (edited output):
```
[umbrella photos]$ ffmpeg -ss 4 -i "./galleries/200_house/96485_bird_calls_at_home/96485.mp4" -vcodec mjpeg -vframes 1 -an -f rawvideo -y "./galleries/200_house/96485_bird_calls_at_home/pwg_representative/96485.jpg" 
ffmpeg version 2.8.7 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.3.1 (GCC) 20160406 (Red Hat 5.3.1-6)

[...]

[swscaler @ 0x14be740] deprecated pixel format used, make sure you did set range correctly

[ ...]
```
The above exits with zero *and* the file is generated, so I'm uncertain that the above run is showing the actual error. apache has write permission in galleries/200_house/96485_bird_calls_at_home/pwg_representative

Any ideas on what's wrong, and how to fix it?

Thanks :)

-- Patrick

**Comment by xbgmsharp** [comment]
Could you please ensure the exit code of ffmpeg is really zero, using ``echo $?``
You can also un-comment line 158, 
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/function_sync2.php#L158

As you can see in line 159, it is either non zero or the file exist.
https://github.com/xbgmsharp/piwigo-videojs/blob/master/include/function_sync2.php#L159

**Comment by patmans** [comment]
OK, un-commenting line 158, and paying more attention, I can see that the file wasn't readable by apache :-(

When I created it as myself, I got that warning and it was black because ... that frame was black.

I then didn't notice the failure in the httpd log output.

Maybe you can run ffmpeg with "-loglevel warning", versus the rather verbose default "-loglevel info", and then log the output on failure?

But it's working for me now. I'll have to be more careful with my workflow :-(

I guess the main piwigo adds the file without actually reading, and so it didn't fail.

**Comment by xbgmsharp** [comment]
Glad heard it does work, I add permission check and add more details to the error message.
Adding the command output for each file, will be quite messy to read.
