### ISSUE TITLE
2.8.a broken obsolete.list leads to corrupted upgrade

### ISSUE THREAD

**Issue by erAck** [xbgmsharp/piwigo-videojs#89]
2.8.a piwigo-videojs/obsolete.list has some weird content, incomplete file names truncated at the left, first two characters seem to be missing starting with the metypes/ entry which likely should be mimetypes/ instead, and even contains a single / entry which might had been js/ ...

That file is used to remove files and directories with admin/include/updates.class.php and it probably removes too many if not all files of a piwigo-videojs installation during an upgrade.

See also the [Piwigo Corrupted?](http://piwigo.org/forum/viewtopic.php?pid=163743#p163743) thread in the Piwigo forum.

**Comment by xbgmsharp** [comment]
Agree this is PWG issue and it is not the first time. I use the git release process from PWG.
Using the zip file Github is safer. 

There is no file call ``admin/include/updates.class.php`` in my source. In fact there is no admin/include directory in the source

**Comment by erAck** [comment]
admin/include/updates.class.php is part of the Piwigo installation. Maybe I misinterpreted and function upgrade_to() is only called for Piwigo upgrades, not for extension upgrades. Check with admin/updates_ext.php and maybe others where updates.class.php is included.

**Comment by mistic100** [comment]
Could you please create a manual release on the extensions repository ? I order to not break everybody galleries (very few people actually know Github is a thing and will come here to download the plugin)

**Comment by plegall** [comment]
@xbgmsharp please see my post on http://piwigo.org/forum/viewtopic.php?pid=163845#p163845

**Comment by xbgmsharp** [comment]
New release 2.8.b, I uploaded in PWG PEM a zip to avoid file corruption.
https://github.com/xbgmsharp/piwigo-videojs/releases/latest
