### ISSUE TITLE
underscore in file name

### ISSUE THREAD

**Issue by cl9m** [xbgmsharp/piwigo-videojs#96]
Hello,

I have a problem
if I have a  _ (underscore) in video's name, video does not load,
if I have - (dashes) or no separation it works.

can you make something please ?

**Comment by xbgmsharp** [comment]
Do you a settingsto allow the ``_`` character?
```
$conf['sync_chars_regex'] = '/^[a-zA-Z0-9-_. ]+$/';
```
Could you clarified ``video does not load``, were you able to sync the video? Can you display all the details on Photo edit properties?

**Comment by cl9m** [comment]
Yes I've
 **$conf['sync_chars_regex'] = '/^[a-zA-Z0-9-_. ]+$/';**
in my confing.inc.php

I can sync the video file and I can edit
I use php7, mysql 5.5
I don't use mediainfo and ffmpeg

sorry I've realized that the problem is not there

exemple don't work : http://nosoov.com/picture/Flashball_le_ping-pong_la_vitesse_de_la_lumiere_1989/category/36-pub

exemple work  : http://nosoov.com/picture/mars_pub/category/36-pub

I don't find the probleme

**Comment by xbgmsharp** [comment]
I am able to play video with underscore without any issue.
Both of you sample don't work me. It is more likely a format issue.
And your webserver return a few HTTP/404.

**Comment by cl9m** [comment]
actually I realize that, I have a problem with my mp4 files, I'll look in this direction
Thanks for your help
